---
title: "Data_Wrangling"
author: "AnnT"
date: "October 22, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)  # install.packages("tidyverse")
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

# inspect the data
gapminder
summary(gapminder)
```
```{r}
library(skimr)  #install.packages("skimr")
skimr::skim(gapminder)
```

```{r}
names(gapminder)  #column names
dim(gapminder)
ncol(gapminder)
nrow(gapminder)

# reverse engineer dim
c(nrow(gapminder), ncol(gapminder))
```
```{r}
# filter by name
names(gapminder)
filter(gapminder, country == "Mexico")
filter(gapminder, lifeExp < 29)
filter(gapminder, country %in% c("Mexico", "Peru", "Brazil"))
filter(gapminder, country == "Mexico", year == 2002)
```
```{r}
y<-filter(gapminder, country == "Sweden")
x <-mean(y$lifeExp)
```

# starting a new chunk

```{r}
select(gapminder, year, lifeExp)
select(gapminder, -continent, -lifeExp)

# use select and filter together
gap_cambodia <- filter(gapminder, country=="Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

# or make this nicer using pipe operator. Completely sucks that you can't use |
gapminder %>% head()
# equivalent to head(gapminder)
gap_cambodia <- filter(gapminder, country=="Cambodia") %>% 
  select(-continent, - lifeExp)
```
```{r}
# mutate adds new variables
gapminder %>% 
  mutate(index = 1:nrow(gapminder))

gapminder %>% 
  mutate(planet = "Earth")

gapminder %>% 
  mutate(gdp = pop * gdpPercap)
```

```{r}
# mutate adds new variables
max_gdp_EV<- gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam")) %>% 
  mutate(max_gdp = max(gdpPercap))
```


Starting second day

```{r}
gap_grouped <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop*gdpPercap,
         max_gdp = max(gdp)) %>% 
  ungroup()
```

^ this is ok but we went up with max_gdp repeating in every row. Let's do the same thing with summarizing.

```{r}
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop*gdpPercap) %>% 
  summarize(max_gdp = max(gdp)) %>% 
  ungroup
```

Example for arrange

```{r}
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop*gdpPercap) %>% 
  summarize(max_gdp = max(gdp)) %>% 
  ungroup() %>% 
  arrange(desc(max_gdp))
```

```{r}
## read in the data. (same URL as yesterday, with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

## explore
co2 %>% head()
co2 %>% dim() # 12

## create new variable that is only 2007 data
gap_2007 <- gapminder %>%
  filter(year == 2007) 
gap_2007 %>% dim() # 142  

## left_join gap_2007 to co2
lj <- left_join(gap_2007, co2, by = "country")

## explore
lj %>% dim() #142
lj %>% summary() # lots of NAs in the co2_2017 columm
lj %>% View() 
```


