---
title: "Graphics_with_ggplot2"
author: "AnnT"
date: "October 22, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Learning ggplot2

We're learning ggplot too. I'm skeptical, but supposedly it will be **awesome**. 



```{r}
library("tidyverse")
#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")
```
Start with the California ('ca') dataset
```{r}
head(ca)
View(ca)
```

Plot visitation to all CA national parks over time
```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors))
```
```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  labs(x = "Year",
       y = "Number of Visitors",
       title = "California National Park Visitation") +
  theme_bw() +  
  theme(legend.title = element_blank()) 

```
```{r}
ggplot(data=se)+
  geom_point(aes(x = year, y = visitors, color = state)) +
  theme_minimal()+
  labs(x = "Year")+
  theme(legend.title = element_blank(), axis.text.x = element_text(angle = 45, size = 14))
```

